# Generated by Django 4.1.4 on 2023-01-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_preferences_breaks_alter_preferences_calls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='emails',
            field=models.IntegerField(),
        ),
    ]
