# Generated by Django 4.1.4 on 2023-01-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_preferences_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='breaks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='calls',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='emails',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='hours',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='meetings',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='breaks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='calls',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='emails',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='hours',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='meetings',
            field=models.CharField(max_length=50),
        ),
    ]
