# Generated by Django 4.1.4 on 2023-01-04 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0005_alter_preferences_user_alter_workdone_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_flagged', models.DateField()),
                ('flag', models.CharField(max_length=50)),
                ('preference', models.CharField(max_length=50)),
                ('work_done', models.CharField(max_length=50)),
                ('action_taken', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaged_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
