# Generated by Django 4.1.4 on 2023-01-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_preferences_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='id',
        ),
        migrations.AddField(
            model_name='preferences',
            name='preference_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
