# Generated by Django 4.1.4 on 2023-01-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_preferences_id_preferences_preference_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flagged',
            options={'ordering': ['date_flagged']},
        ),
        migrations.AlterModelOptions(
            name='workdone',
            options={'ordering': ['date']},
        ),
    ]
