# Generated by Django 4.1.4 on 2023-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_flagged_user_alter_preferences_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='preference_id',
        ),
        migrations.AddField(
            model_name='preferences',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
